plugins {
    id 'java'
}

group = 'tash.tests'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // RestAssured for API testing
    implementation 'io.rest-assured:rest-assured:5.4.0'

    // Allure
    testImplementation 'io.qameta.allure:allure-junit5:2.27.0'
    testImplementation 'io.qameta.allure:allure-rest-assured:2.27.0'

    // Jackson for JSON processing
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'

    // AssertJ for better assertions
    testImplementation 'org.assertj:assertj-core:3.25.3'
}

// Настройка задачи test
test {
    useJUnitPlatform()
}